services:
  proposal:
    build: .
    command: make
    working_dir: /main
    volumes:
      - './whitepaper/proposal:/main'
      - './output:/output'
  final:
    build: .
    command: make
    working_dir: /main
    volumes:
      - './whitepaper/final:/main'
      - './output:/output'
  shell:
    build: .
    command: bash
    working_dir: /main
    volumes:
      - './whitepaper:/main'
      - './output:/output'
